/**
 * `extractPdfMarkdown` — text-layer extraction, scanned (no-text-layer)
 * success, page-marker join format, and corrupt-PDF failure.
 *
 * Fixtures under `test/fixtures/pdf/` are hand-crafted minimal PDFs (a few
 * hundred bytes each) generated by `test/fixtures/pdf/build.ts`. Extraction
 * runs against the real fixture bytes on disk — it is local compute, not a
 * network call, so nothing is mocked here.
 */

import { describe, expect, test } from "bun:test";
import { PdfExtractionError, extractPdfMarkdown } from "../../src/vault/pdfText.ts";
import { loadPdfFixture } from "../helpers/loadPdfFixture.ts";

describe("extractPdfMarkdown", () => {
  test("extracts a two-page text layer with a page marker between pages", async () => {
    const out = await extractPdfMarkdown(loadPdfFixture("text.pdf"));
    expect(out.pages).toBe(2);
    expect(out.hasTextLayer).toBe(true);
    // Page 1 text, then the marker for the FOLLOWING page (2), then page 2 —
    // no marker precedes page 1.
    expect(out.markdown).toBe("alpha\n\n<!-- page 2 -->\n\nbeta");
  });

  test("drops an image-only page between two text pages, keeping physical page numbers", async () => {
    // mixed.pdf: "alpha" (page 1), empty/image-only (page 2), "gamma" (page 3).
    // The empty page is omitted from the join and "gamma" keeps its own page
    // number (3) in the marker — no 4-newline blank run, no marker at page 2.
    const out = await extractPdfMarkdown(loadPdfFixture("mixed.pdf"));
    expect(out.pages).toBe(3);
    expect(out.hasTextLayer).toBe(true);
    expect(out.markdown).toBe("alpha\n\n<!-- page 3 -->\n\ngamma");
  });

  test("a leading image-only page still emits its follower's marker without a blank prefix", async () => {
    // mixed-leading.pdf: empty/image-only (page 1), "beta" (page 2). The first
    // emitted page is page 2, so its marker is present and there is no leading
    // blank run.
    const out = await extractPdfMarkdown(loadPdfFixture("mixed-leading.pdf"));
    expect(out.pages).toBe(2);
    expect(out.hasTextLayer).toBe(true);
    expect(out.markdown).toBe("<!-- page 2 -->\n\nbeta");
  });

  test("scanned PDF with no text objects succeeds with hasTextLayer false", async () => {
    const out = await extractPdfMarkdown(loadPdfFixture("scanned.pdf"));
    expect(out.hasTextLayer).toBe(false);
    expect(out.markdown).toBe("");
    expect(out.pages).toBeGreaterThanOrEqual(1);
  });

  test("corrupt PDF throws a typed PdfExtractionError with the shared code", async () => {
    const promise = extractPdfMarkdown(loadPdfFixture("broken.pdf"));
    await expect(promise).rejects.toBeInstanceOf(PdfExtractionError);
    await expect(promise).rejects.toMatchObject({
      code: "extraction_failed",
      message: expect.stringContaining("failed to parse PDF"),
    });
  });
});
